version: '3.9'

services:

  youtube-frontend-dev:
    container_name: youtube-frontend-dev
    build: 
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    ports:
      - '3001:3000'
