version: '3.9'

services:
  youtube-frontend:
    container_name: youtube-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    ports:
      - '8081:80'
  