name: Docker Dev Image CI

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Auto-merge
        uses: reitermarkus/automerge@v1.5.2

      - name: Bump version number
        run: |
          git config --global user.email "ea.giovanniello@gmail.com"
          git config --global user.name "Elizabeth Giovanniello"
          git pull origin devOps
          git checkout devOps
          npm version patch
          git push -u origin devOps
          git push --tags
