name: Docker Dev Image CI

on: 
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Auto-merge 
        uses: reitermarkus/automerge@v1.5.2

      - name: Bump version number
        run: |
              git config --global user.email "ea.giovanniello@gmail.com"
              git config --global user.name "Elizabeth Giovanniello"
              npm version patch
              git push --tags


      # - name: Run Docker Compose on Dev Files
      #   run: docker-compose -f "docker-compose-dev.yml" up -d --build

      # - name: Bump version and push tag
      #   uses: TriPSs/conventional-changelog-action@v3

      # - name: version
      #   run: npm version patch -m "[RELEASE] %s"
      #   run: git push

      # - name: Create a Release
      #   uses: actions/create-release@v1
      #   with: 
      #     draft: false
      #     prerelease: false
      #     release_name: ${{ github.ref }}
      #     tag_name: ${{ github.ref }}
      #     body_path: CHANGELOG.md
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
          

      


      